### ISSUE TITLE
接口跑不通。。。

### ISSUE THREAD

**Issue by stevending1st** [open-jike/jike-sdk#64]
```json
// package.json
{
  "name": "web3test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jike-sdk": "^0.7.0"
  },
  "type": "module"
}
```

```js
// index.mjs
import { api, setAccessToken, ApiClient } from 'jike-sdk/node'

setAccessToken('这里是我的 TOKEN') //TOKEN 取的是在 Cookie 里的 x-jike-access-token 或者 x-jike-refresh-token
api.userRelation.getFollowingList('82D23B32-CF36-4C59-AD6F-D05E3552CBF3', {
  limit: 100,
})
```

执行：
```npm
node index.mjs
```

返回报错：
```
.../web3test/node_modules/jike-sdk/dist/node.mjs:97
}, setAccessToken = (token2) => apiConfig.accessToken = token2, getAccessToken = () => apiConfig.accessToken, _request, request = new Proxy(() => {                                                       ssToken, _request, request = new Proxy(() => {   
                                                      ^

TypeError: Cannot set property 'accessToken' of undefined
    at setAccessToken (.../web3test/node_modules/jike-sdk/dist/node.mjs:97:55)
    at .../web3test/index.mjs:7:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
```

**Comment by sxzz** [comment]
为了规避部分风险，已将即刻相关配置剥离，需要自行配置

**Comment by stevending1st** [comment]
> 为了规避部分风险，已将即刻相关配置剥离，需要自行配置：

是否考虑修改文档

**Comment by sxzz** [comment]
@stevending1st 有在考虑，但是本就是为了规避风险，后续处理。

**Comment by sxzz** [comment]
> > 为了规避部分风险，已将即刻相关配置剥离，需要自行配置：
> 
> 是否考虑修改文档

已更新
